Search lyrics from terminal!
brenns10/tswift pull request #3
Opened 2016-07-20 05:37 UTC by a-johnston

Very cool! Adds a dependency though. Also noticed that you didn't update changelog with the last PR.

2016-09-05 16:18 UTC, brenns10 commented
Couple things that need to be changed before this PR can be accepted.
- [ ] Need to have google added to the `install_requires` list in `setup.py`.
- [ ] Need to place `find_song` and the CLI code into `tswift.py` (you can replace the original CLI for tswift since it isn't very good).  If you really prefer to have it as a separate file then it needs to be within a _package_ named `tswift` first, so there's plenty of code movement either way.
- [ ] Need to declare a CLI entrypoint for this in `setup.py`.  See [here](http://python-packaging.readthedocs.io/en/latest/command-line-scripts.html) for docs about this - I prefer `console_scripts` over just `scripts`, but that's just me.
- [ ] Will need a version bump in setup.py to go with this (you can put all the updates under that heading in the changelog).

If you'd prefer me to make these changes (since they're mostly to do with packaging) I can merge and do it myself.  Otherwise I'll wait on more commits :)

2016-09-06 00:00 UTC, a-johnston commented
Before reviving this pr (which I made mainly to bug you with notifications and because I was already playing around with it), does this CLI tool _really_ have a place in the beautifully simple tswift module? I feel like we would be causing our users some pain by giving them a CLI script when they try installing this. It confuses the boundary between tswift specific, song agnostic to potentially song specific, artist agnostic.

2016-09-06 04:50 UTC, brenns10 commented
> does this CLI tool really have a place in the beautifully simple tswift module?

Sounds like you're just trying to weasel your way out of work :P

I would personally have no problem modifying this concept slightly with command line flags, eg:
- `-S` finds first song that matches your search query and prints lyrics
- no flag: acts as before

Or something like that.

2017-03-02 19:01 UTC, brenns10 requested changes
See review comments. I'm expecting changes soon :)

2017-03-02 19:01 UTC, brenns10 commented on CHANGELOG.md
> +
Move this to the Unreleased section. I'll can make a release after this.

2017-03-02 19:01 UTC, brenns10 commented on lyrics.py
> +def find_song(lyrics):
This function should be a class method of `Song`. That way library users can benefit from `Song.find_song('lyrics')`.

2017-03-02 19:01 UTC, brenns10 commented on lyrics.py
> +        print(song.format() if song else 'No song found :(')
Instead of a separate script, make this part of the CLI of `tswift.py`, using a switch like `-S`. You'll probably have to use `argparse`.

2017-03-02 19:01 UTC, brenns10 commented on requirements.txt
> +google>=1.9.1
Don't forget to add this to `install_requires` in `setup.py`.

2017-03-02 19:11 UTC, a-johnston commented on lyrics.py
> +        print(song.format() if song else 'No song found :(')
what if some artist takes on the name "-S"? should the current CLI be deprecated in favor of more explicit parameters?

2017-03-02 19:31 UTC, brenns10 commented on lyrics.py
> +        print(song.format() if song else 'No song found :(')
argparse follows the standard convention that you can stop option parsing and move on to literal strings by passing a double hyphen. e.g.

    rm -- -rf

will delete the file `-rf`. Similarly, `tswift -- -S` would search for artist `-S`

2017-03-02 19:32 UTC, brenns10 commented on lyrics.py
> +        print(song.format() if song else 'No song found :(')
don't you try to avoid work with these silly corner cases!
show me an artist named `-S`!

2017-03-02 19:45 UTC, brenns10 approved these changes

2017-03-02 19:46 UTC, brenns10 commented
Anything else to add? I can merge now.

2017-03-02 19:50 UTC, a-johnston commented
Yeah, I updated readme and realized the old behavior is broken as artist is no longer positional, which I'm fixing atm. Lots of rtfm since I haven't used argparse in a while/ever

2017-03-02 20:03 UTC, a-johnston commented
Done with updates if it lgty

2017-03-02 20:14 UTC, brenns10 commented
lgtm

2017-03-02 20:14 UTC, merged